class ParameterCodes(object):
	Security_DigitalSignatures=6
	Input_SeedSpectrum=7
	Input_SeedVariate=8
	Simulator_Enable=9
	UPnP_FriendlyName=10
	Time_TimeZone=11
	Time_CorrectForDaylightSavings=12
	Network_IPAddress=13
	Network_EnableDHCP=14
	Network_Gateway=15
	Network_Subnet=16
	Network_DNSAddress=17
	Network_DNSAlternateAddress=18
	Network_WINSAddress=19
	Network_WINSAlternateAddress=20
	Network_RAS_Enable=21
	Network_RAS_User=22
	Network_RAS_Password=23
	Network_RAS_Subnet=24
	Network_RAS_IPAddress=25
	Configuration_MaximumNumberOfClients=26
	Network_TimeSynchronization_Enable=27
	Network_TimeSynchronization_ServerAddress=28
	Network_TimeSynchronization_RefreshRate=29
	Network_TimeSynchronization_Threshold=30
	Network_TimeSynchronization_RecoveryRefreshRate=31
	System_StorageLimit=32
	AuditManager_Storage_MaxSize=33
	AuditManager_Enable=34
	Localization_LCID=35
	Watchdog_Enable=36
	Watchdog_TimeOut=37
	Preset_Options=38
	Preset_Live=39
	Preset_Real=40
	Preset_StartChan=41
	Preset_EndChan=42
	Input_Name=43
	Input_Owner=44
	Input_LockState=45
	Input_NumberOfGroups=46
	Input_CurrentGroup=47
	System_NumberOfInputs=48
	Calibrations_Energy_Offset=49
	Calibrations_Energy_Slope=50
	Calibrations_Energy_Quad=51
	Calibrations_FWHM_SquareRoot_Offset=52
	Calibrations_FWHM_SquareRoot_Slope=53
	Calibrations_FWHM_Poly_Offset=54
	Calibrations_FWHM_Poly_Slope=55
	Calibrations_FWHM_Poly_Quad=56
	Calibrations_FWHM_CurrentModel=57
	Calibrations_LowTail_Poly_Offset=58
	Calibrations_LowTail_Poly_Slope=59
	Input_Mode=60
	Input_Status=61
	Preset_Totals=62
	Preset_Sweeps=63
	Elapsed_Totals=64
	Elapsed_Sweeps=65
	Elapsed_Live=66
	Elapsed_Real=67
	Input_StartTime=69
	Input_NumberOfChannels=70
	Input_Capabilities=71
	Input_RoiUncMult=72
	Input_RoiNumBkgChans=73
	Network_RNDIS_EnableDHCP=75
	Network_RNDIS_Gateway=76
	Network_RNDIS_Subnet=77
	Network_RNDIS_IPAddress=78
	Webserver_LoginEnabled=79
	System_SerialNumber=80
	Network_MachineName=81
	System_DateTime=82
	UPnP_TimeToLive=83
	UPnP_Enable=84
	Webserver_Enable=86
	Webserver_MaximumNumberOfClients=87
	Configuration_Port=91
	Configuration_SessionTimeout=92
	DSO_CaptureInterval=94
	DSO_SampleRate=95
	DSO_TriggerLevel=96
	DSO_NumberOfPreTriggerSamples=97
	DSO_NumberOfPostTriggerSamples=98
	DSO_TriggerSource=99
	DSO_TriggerSlope=100
	DSO_Simulate=101
	DSO_Variate=102
	DSO_NumberOfAnalogSignals=103
	DSO_NumberOfDigitalSignals=104
	DSO_EnableCapture=105
	UPnP_DeviceType=106
	UPnP_ModelDescription=107
	UPnP_ModelName=108
	UPnP_ModelNumber=109
	UPnP_ModelSerialNumber=110
	UPnP_ServiceType=111
	UPnP_ServiceID=112
	UPnP_PresentationURL=113
	UPnP_MajorVersion=114
	UPnP_MinorVersion=115
	UPnP_UPC=116
	UPnP_UDN=117
	Network_EnableRouting=119
	Network_RAS_BaudRate=120
	Network_FTP_Enable=123
	Network_FTP_UserList=124
	Network_FTP_DefaultDir=125
	Network_FTP_UseAuthentication=126
	Network_FTP_AllowAnonymousUpload=127
	System_RebootTimeOut=136
	System_MemoryLimit=137
	System_StorageTimeLimit=138
	Input_DisplayRois_Start=139
	Input_DisplayRois_End=140
	Input_DisplayRois_Type=141
	Security_UserNames=142
	Security_Passwords=143
	Input_FineGain=145
	Network_Wireless_IPAddress=146
	Network_Wireless_EnableDHCP=147
	Network_Wireless_Gateway=148
	Network_Wireless_Subnet=149
	Network_Wireless_DNSAddress=150
	Network_Wireless_DNSAlternateAddress=151
	Network_Wireless_WINSAddress=152
	Network_Wireless_WINSAlternateAddress=153
	Input_CoarseGain=154
	Input_Attenuate=155
	Input_PoleZero=157
	Input_Voltage=158
	Input_VoltageRange=159
	Input_VoltagePolarity=160
	Input_VoltageStatus=161
	Input_VoltageInhibitControl=162
	Input_VoltageInhibitPolarity=163
	Input_VoltageRamping=164
	Input_VoltageFault=165
	Input_VoltageReading=166
	Input_VoltageLimit=167
	Input_VoltageState=169
	Input_Spectrum=170
	DSO_NumberOfSweeps2Avg=171
	DSO_TriggerMode=172
	System_ResetButtonPressed=173
	DSO_Flags=174
	DSO_AnalogSignalsMask=175
	Security_UserDescriptions=176
	Security_UserPrivileges=177
	System_Rebooting=178
	Network_Wireless_SSID=179
	Network_Wireless_InfrastructureMode=180
	Network_Wireless_Encryption=181
	Network_Wireless_Authentication=182
	Network_Wireless_Key=183
	Network_Wireless_KeyIndex=184
	Network_Wireless_KeyAuto=185
	Network_Wireless_EapType=186
	Input_Dwell=187
	DSO_TriggerStatus=188
	DSO_DataAvailable=189
	DSO_ExcessivePileup=190
	DSO_SampleCount=191
	DSO_Capture=192
	Input_FilterMode=193
	Input_SlowRiseTime=194
	Input_SlowFlatTop=195
	Input_PoleZeroError=200
	System_AppBasePath=202
	System_FirmwareVersion=203
	DSO_Resolution=204
	Input_DiscMode=205
	Input_DiscROIStart=206
	Input_DiscROIEnd=207
	Counter_GateTimer=208
	Counter_TestPulser=210
	Counter_ExternalSyncMode=211
	Counter_AcquisitionInterval=212
	Counter_Mode=213
	Input_CoincGateMode=215
	Input_CoincGatePolarity=216
	Input_CoincGateDelay=217
	Input_StabilizerGainCorrRange=218
	Input_StabilizerGainMode=219
	Input_StabilizerGainStatus=220
	Input_StabilizerCorrDivider=221
	Input_StabilizerSpacing=222
	Input_StabilizerWindow=223
	Input_StabilizerRatioMode=224
	Input_StabilizerCorrectionValue=225
	Input_StabilizerManualRatio=226
	Input_StabilizerCentroid=227
	Input_McsExternalControlMode=228
	Input_McsExternalControlPolarity=229
	Input_McsExternalControl=230
	Input_DigitalOffset=231
	Input_PhaExternalControlMode=232
	Input_PhaExternalControlPolarity=233
	Input_PhaExternalControl=234
	Input_BLRmode=235
	Input_PreampType=236
	Input_FastDiscShaping=237
	Input_FastDiscMode=238
	Input_FastDisc=239
	Input_LLDmode=240
	Input_LLD=241
	Input_ULD=242
	Input_PURguard=243
	Input_LTtrim=244
	Input_PURLTCmode=245
	Input_Polarity=246
	Input_Countrate=247
	Input_TRPInhibitmode=248
	Input_TRPInhibit=249
	Input_TRPGatepolarity=250
	Input_ChangerAdvPolarity=251
	Input_ChangerReadyPolarity=252
	Counter_Status=253
	GPIO1_Control=254
	GPIO2_Control=255
	GPIO3_Control=256
	GPIO4_Control=257
	GPIO1_Input=258
	GPIO2_Input=259
	GPIO3_Input=260
	GPIO4_Input=261
	Input_ExternalSyncStatus=263
	Input_ExternalSyncMode=264
	Input_ExternalSyncPulse=265
	Input_ExternalSyncTimeO=266
	Input_ExternalSyncPolarity=267
	Network_WirelessBoundAddress=268
	Network_WiredBoundAddress=269
	Input_ChangerReady=270
	Input_Deadtime=271
	Input_RWregister=272
	Network_RAS_ModemCmdSndDelay=273
	Input_McsExternalChanAdvMode=274
	Input_McsExternalChanAdvPolarity=275
	Input_McsExternalSweepAdvMode=276
	Input_McsExternalSweepAdvPolarity=277
	Input_MonitorControl=278
	Security_UserTypes=280
	System_DiagnosticsOptions=281
	Input_ListMode=282
	Input_ListBufferSize=284
	System_DiagnosticsEnableOptions=286
	Input_Fault=287
	Input_LastError=288
	Input_AutoPoleZeroValue=289
	System_StorageSettings=290
	Input_ElapsedAcqStartTime=291
	System_DriverVersion=292
	System_FpgaVersion=293
	Input_TestPulserEnabled=294
	Input_TestPulserRate=295
	Input_TestPulserFrequency=296
	Input_TestPulserAmplitude=297
	Streaming_Port=298
	Streaming_SessionTimeout=299
	Streaming_MaximumNumberOfClients=300
	Streaming_Enable=301
	Streaming_Data=302
	Network_Wireless_MAC=303
	Network_Wired_MAC=304
	Input_ListAcqOptions=305
	Input_SCAlld=306
	Input_SCAuld=307
	Input_SCAbuffer=308
	Input_SCAacqInterval=309
	Input_SCApresetMode=310
	Input_SCAmode=311
	Input_SCAstatus=312
	Network_RadnetPort=313
	Network_RadnetMulticastAddress=314
	Network_RadnetMulticastTTL=315
	Network_RadnetEnable=316
	System_StorageOptions=317
	System_StorageMediaState=318
	Counter_BufferSize=319
	Input_SCAbufferSize=320
	Input_MSSbufferSize=321
	Input_ActiveGroup=322
	Input_SCAexternalSyncMode=323
	Input_MSSexternalSyncMode=324
	Network_RadnetInstrumentID=325
	Network_RadnetInstrumentLocation=326
	Network_RadnetInput=327
	Network_RadnetEnableBroadcast=328
	Input_SlowDiscMode=329
	Input_SlowDisc=330
	Input_FastShaperHighThreshold=331
	Input_SlowShaperHighThreshold=332
	Input_Configuration=333
	Input_PhaExternalControlOut=334
	Input_McsExternalControlOut=335
	Input_CoincPredelay=336
	Input_CoincGatePulseWidth=337
	Input_FastDiscExtension = 338
	Input_SlowDiscExtension = 339
	Input_FastDiscSGateExtension = 340
	Input_SlowBlrTimeConstant = 341
	Input_FastBlrTimeConstant = 342
	Input_FastRiseTime = 343
	Input_FastFlatTop = 344
	Input_BlrHardwareMode = 345
	Input_FastNormalMultiplier = 346
	Input_FastLowMultiplier = 347
	Input_SlowNormalMultiplier = 348
	System_MFactor = 349
	Input_DifferentiatorTC = 350
	System_MFactorDefault = 351
	System_AdminPassword = 352
	System_AnonymousPassword = 353
	System_ThermistorInput = 354
	Input_ChangerAdvancePulse = 355
	Input_SuperFineGain = 356
	System_ManufacturingInfo = 357
	System_AnalogReading1 = 358
	System_AnalogReading2 = 359
	System_AnalogReading3 = 360
	System_AnalogReading4 = 361
	System_AnalogReading5 = 362
	System_AnalogReading6 = 363
	System_AnalogReading7 = 364
	System_AnalogReading8 = 365
	System_AnalogStatus1 = 366
	System_AnalogStatus2 = 367
	System_AnalogStatus3 = 368
	System_AnalogStatus4 = 369
	System_AnalogStatus5 = 370
	System_AnalogStatus6 = 371
	System_AnalogStatus7 = 372
	System_AnalogStatus8 = 373
	#---- New Aegis specific parameters are below this line
	System_EthernetEnable = 374			#Ethernet is enabled
	System_AcmRevision = 375					#ACM Revision level
	Input_MSSsegmentCount=377		# (0)	The MSS segment count
	Input_OverloadRecoveryExt=378		# (0)	Overload Recovery extension time in uS
	System_RegisterRW_Adrs=380		#			Diagnostic register r/w physical address
	System_RegisterRW_Value=381		#			Diagnostic register r/w data value
	System_RegisterRW_Type=382		#			register r/w addrs type: determines type of access 0= U8 1= U16 2= U32
	System_TPLogCount=383		#			On read reports number of entries currently in the system log ranging from 0 (empty) up to maximum of approximately 1000. On write if the value is non-zero it will reset the system log
	System_TPLogData=384		#			all entries currently in the system log
	Calibrations_Energy_Cubic = 386			# (0.0)	The cubic energy component
	Calibrations_Energy_Quartic = 387		# (0.0)	The quartic energy component
	Calibrations_HighTail_Poly_Offset = 388	# (0.0)	The high tail poly model offset
	Calibrations_HighTail_Poly_Slope = 389	# (0.0)	The high tail poly model slope
	PAR_AEM_ADJ_CSAGain=390		# (1)	Sets Gain multiplier to 1 2 5 or 10
	PAR_AEM_ADJ_PoleZero=391		# (1.0)	AEM P/Z setting
	PAR_AEM_ADJ_FETDrainCurrent=392		# (0)	FET Current setting
	PAR_AEM_DAC_OStageDCOffset=393		# (-1)	Output Stage DC Offset
	PAR_AEM_DAC_FETBackgateV=394		# (-23.5)	FET Backgate Voltage
	PAR_AEM_DAC_FETDrainV=395		# (2)	FET Drain Voltage
	PAR_AEM_DAC_TestPulserRefVoltage=396		# (0)	Pulser Reference Voltage
	PAR_AEM_Par_PulserClockEnable=397		# (0)	Pulser Clock Enable
	PAR_AEM_Par_SelectExtPulser=398		# (0)	External Pulser Select
	PAR_AEM_Par_SelectPulserPolarity=399		# (0)	External Pulser Polarity (0=pos 1= neg)
	AR_AEM_Par_PulserFrequency=400		# (100)	Pulser Frequency Selection
	PAR_AEM_Par_OutputPolarity=401		# (1)	Output Polarity Select (0=pos 1= neg)
	PAR_AEM_Par_DetAcCoupled=402		# (1)	Detector AC coupling select
	PAR_AEM_Par_DetLeakageCurrentZeroOffset=403		# (0)	Detector Leakage Offset
	PAR_AEM_Par_CSARfb=404		# (0)	CSA Feedback Resistor Value
	PAR_AEM_Par_NominalCSADCLevel=405		# (0)	CSA nominal DC Level Volts
	PAR_AEM_Par_ACLeakageCurrentHighLimit=406		# (1000)	AC Leakage Current High Limit
	PAR_AEM_Par_DCLeakageCurrentHighLimit=407		# (1000)	DC Leakage Current High Limit
	PAR_AEM_ADC_ChargeLoopAvgDCLevel_Offset=408		# (0)	PAR_AEM_ADC_ChargeLoopAvgDCLevel_Offset
	PAR_AEM_ADC_OStageDCOffset_Offset=409		# (0)	ADC Output stage DC Offset
	PAR_AEM_ADC_DetectorLeakageCurrent=410		#			AC Detector leakage current
	PAR_AEM_ADC_ChargeLoopAvgDCLevel=411		#			Charge loop average DC level
	PAR_AEM_ADC_OStageDCOffset=412		#			Output stage DC offset
	PAR_AEM_ADC_FETBackgateVoltage=413		#			FET Backgate Voltage
	PAR_AEM_ADC_FETDrainVoltage=414		#			FET Drain Voltage
	PAR_AEM_ADC_TestPulserRefVoltage=415		#			Test Pulser Reference Voltage
	PAR_AEM_AEM_SystemStatus=416		#			AEM Status bitmap
	PAR_AEM_Par_AEMFirmwareVersion=417		#			Firmware Version constant
	PAR_AEM_Par_DCLeakageCurrent=418		#			DC Detector leakage current
	PAR_AEM_DeviceReadDirect=419		#			Reads An AEM device parameter directly. Accepts AEM-native parameter code
	PAR_AEM_DiagErrCounter=420		#			Reads the AEM's communication error counter for diagnostic purposes. Reset by ClearFaults
	PAR_AEM_DiagCmdCounter=421		#			Reads the AEM's communication command counter for diagnostic purposes. Reset by ClearFaults
	PAR_AEM_Par_AllReadings=422    #          Returns all readings as a series of <space> separated  name=value pairs
	PAR_PM_SystemStatus=430		#			Returns status faults system time temperature voltages and currents from the power manager hardware. Returned string is comma-separated and null-terminated.
	PAR_PM_SystemFaults=431		#			When read returns bitmap of PM faults. When writing resets PM faults (any non-zero value can be used when writing).
	PAR_PM_VersionInfo=432		#			Returns version and build information from the power manager hardware.
	PAR_PM_CDEStatus=433       #  Writes the current status of the CDE to the power manager
	PAR_PM_AccThreshold=434    #  Writes thresholds for the power managers accelerometer XYZ
	PAR_PM_PowerOnReset=437    # If 1 the PMGR will turn on power after a hard reset; otherwise power will stay off (not persistent)
	PAR_CDE_SystemStatus=440		#			current CDE status
	PAR_CDE_SystemFaults=441		#			current CDE faults
	PAR_CDE_TargetTemperature=442		# (90)	target temperature in Kelvin
	PAR_CDE_ColdTipTemperature=443		#			cold-tip temperature in Kelvin
	PAR_CDE_SkinTemperature=444		#			skin-tip temperature in Kelvin
	PAR_CDE_CoolingStatus=445		#			See CDECoolingStatus enum
	PAR_CDE_AVREnable=446		#			Enable/Disable control for the Active Vibration Reduction system
	PAR_CDE_AVRStatus=447		#			See CDEAvrStatus enum
	PAR_CDE_VersionInfo=448		#			application version  information from CDE
	PAR_CDE_WorkingTime=449		#			CDE working time in minutes
	PAR_CDE_Summary=450    #  CDE status summary: space-separated name=value pairs
	PAR_CDE_BuildInfo=451		#			application build information
	PAR_CDE_DeviceSettingId=452		#			Specifies native code for reading and writing FRAM settings in CDE hardware. See   CDEDeviceSettingsNative enum
	PAR_CDE_DeviceSettingValue=453		#			Reads or writes a FRAM value from/to the CDE hardware using the ID specified through parameter  PAR_CDE_DeviceSettingId
	PAR_CDE_DiagErrCounter=454		#			Reads the CDE's communication error counter for diagnostic purposes. Reset by ClearFaults
	PAR_CDE_DiagCmdCounter=455		#			Reads the CDE's communication command counter for diagnostic purposes. Reset by ClearFaults
	PAR_CDE_Control = 456  #  Sets the CDE status to 0=OFF 1= ON/Automatic 2= ON/Manual
	PAR_CDE_DetectorTemperature = 458  # Detector temperature in degrees C
	PAR_CDE_ColdHeadTemperature = 459  # Coldhead temperature in degrees C
	PAR_ION_Status=460		#			Ion Pump On/Off
	PAR_ION_VoltSetting=461		# (0)	Ion Pump Voltage Setting
	PAR_ION_Readings=462		#			Returns all Ion Pump readings as space-separated "name=value" pairs
	PAR_ION_Faults=463		#			Returns current Ion Pump faults; any write clears.
	PAR_System_PeripheralControl = 465  #  Enables or disables periodic polling related interactions between main controller (MCA) and system peripherals
